default: &default
  adapter: mysql2
  username: username
  password: password
  host: host

development:
  <<: *default
  database: database_development

test:
  <<: *default
  database: database_test
